version: "3.3"

services:
   dcrd:
     container_name: dcrd
     build:
       context: dcrd/
     volumes:
       - shared:/config
       - decred:/data
     environment:
       - RPCUSER
       - RPCPASS
       - NETWORK
       - DEBUG
       - MINING_ADDRESS
     networks:
       - dcr-network
     entrypoint: ["./start-dcrd.sh"]

   dcrwallet:
     container_name: dcrwallet
     build:
       context: dcrwallet/
       args:
         WALLET_SEED: "0000000000000000000000000000000000000000000000000000000000000000"
         WALLET_PASS: "123"
     volumes:
       - shared:/rpc
       - decred:/data
     environment:
       - RPCUSER
       - RPCPASS
       - NETWORK
     networks:
       - dcr-network
     entrypoint: ["./start-dcrwallet.sh"]

   dcrlnd:
     build:
       context: ../
       dockerfile: docker/dcrlnd/Dockerfile
     environment:
       - RPCUSER
       - RPCPASS
       - NETWORK
       - DEBUG
     networks:
       - dcr-network
     volumes:
       - shared:/rpc
     entrypoint: ["./start-dcrlnd.sh"]

volumes:
  # shared volume is need to store the dcrd rpc certificates and use it within
  # dcrctl and dcrlnd containers.
  shared:
    driver: local

  # decred volume is needed for maintaining blockchain persistence
  # during dcrd container recreation.
  decred:
    driver: local

networks:
  dcr-network:
    driver: bridge
